version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd server
      - npm install
      - npm run build # if you have a build step
      - cd ..
      - mkdir -p build
      - cp -R server/* build/
      - cd build
      - zip -r ../application.zip .
      - cd ..
      - echo "Created ZIP file with Express app at root"
      - ls -la application.zip

artifacts:
  files:
    - application.zip