version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd server
      - npm install
      - npm run build # if you have a build step
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - server/**/*
    - .ebextensions/**/*
    - .platform/**/*